name: Unit tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - 'feature/**'
      - 'refactor/**'

jobs:
  core_unit_tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Run proprium-core unit tests
        run: cargo test -p proprium-core