name: Unit tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - 'feature/**'
      - 'refactor/**'

jobs:
  core_unit_tests:
    runs-on: [self-hosted]
    steps:
      - name: Install Rust and Cargo (if not already installed)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 

      - name: Add Cargo to PATH
        run: echo "::add-path::$HOME/.cargo/bin"

      - name: Run proprium-core unit tests
        uses: actions/checkout@v3
        run: cargo test -p proprium-core
